"""Add Deliverer table

Revision ID: 36a96f29e834
Revises: f2b8b767218a
Create Date: 2022-12-13 10:12:33.948241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a96f29e834'
down_revision = 'f2b8b767218a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Deliverers',
    sa.Column('netid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('netid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Deliverers')
    # ### end Alembic commands ###
