"""Make `Users.address` nullable

Revision ID: 896ed19beee3
Revises: 2c147dfbbe3a
Create Date: 2022-12-14 00:40:44.019382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896ed19beee3'
down_revision = '2c147dfbbe3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # make a local Table object
    table = sa.Table(
        'Users',
        sa.MetaData(),
        sa.Column('netid', sa.Integer, primary_key=True),
        sa.Column('address', sa.VARCHAR()))
    # update all rows to have a non-null value
    connection = op.get_bind()
    connection.execute(table.update().values(address=''))

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(),
               nullable=False)
