"""Initial migration

Revision ID: a0b6a87db8eb
Revises: 
Create Date: 2022-12-11 15:00:48.181877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b6a87db8eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserProfiles',
    sa.Column('netid', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('netid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserProfiles')
    # ### end Alembic commands ###
