"""Add Orders table

Revision ID: f2b8b767218a
Revises: db54ffa7fbbb
Create Date: 2022-12-11 22:14:24.219977

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f2b8b767218a'
down_revision = 'db54ffa7fbbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('netid', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('kiosk', sa.String(length=5), nullable=False),
    sa.Column('pin', sa.String(length=6), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('delivery_netid', sa.String(), nullable=True),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.Column('date_delivered', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Orders')
    # ### end Alembic commands ###
